const stopWords = new Set([
    // -- Common 'Round-Up' or 'Top Picks' Words
    "top",
    "best",
    "leading",
    "major",
    "roundup",
    "roundups",
    "picks",
    "list",
    "lists",
  
    // -- Common Marketing/Promotional Superlatives & Fluff
    "ultimate",
    "complete",
    "comprehensive",
    "amazing",
    "fantastic",
    "incredible",
    "awesome",
    "wonderful",
    "excellent",
    "unbelievable",
    "outstanding",
    "greatest",
    "remarkable",
    "unmatched",
    "unparalleled",
    "unparalled", // sometimes misspelled
    "state-of-the-art",
    "innovative",
    "revolutionary",
    "breakthrough",
    "cutting-edge",
    "groundbreaking",
    "modern",
    "advanced",
    "genius-level",
    "miraculous",
    "miracle",
    
    // -- “Need to Know” / “Essential” Keywords
    "must-have",
    "essential",
    "crucial",
    "vital",
    "critical",
    "key",
    "need-to-know",
    "urgent",
    "must-read",
    "in-demand",
    
    // -- Comparisons / Rankings
    "ranking",
    "rankings",
    "comparison",
    "comparisons",
    "versus",
    "vs",
    "highest-rated",
    "top-rated",
    "favorite",
    "favorites",
    
    // -- Tutorials, Guides, & Overviews
    "how-to",
    "how to",
    "tutorial",
    "tutorials",
    "step-by-step",
    "manual",
    "guide",
    "guides",
    "playbook",
    "blueprint",
    "roadmap",
    "checklist",
    "demystified",
    "decoded",
  
    // -- Reviews, Summaries, & Explanations
    "review",
    "reviews",
    "analysis",
    "analyses",
    "breakdown",
    "breakdowns",
    "study",
    "report",
    "reporting",
    "summary",
    "summaries",
    "conclusion",
    "conclusions",
    "explanation",
    "explanations",
  
    // -- “Tips,” “Tricks,” & Helpers
    "tips",
    "tricks",
    "secrets",
    "hacks",
    "hack",
    "methods",
    "method",
    "techniques",
    "strategy",
    "strategies",
    "tactics",
    "best practices",
    "shortcut",
    "shortcuts",
  
    // -- “Expert,” “Pro,” “Master,” etc.
    "expert",
    "experts",
    "expert-level",
    "pro",
    "professional",
    "specialist",
    "master",
    "masterclass",
    "mastery",
    "guru",
    
    // -- Catch-All Marketing Words
    "recommended",
    "recommendations",
    "exclusive",
    "premium",
    "proven",
    "results",
    "success",
    "dominate",
    "accelerate",
    "enhance",
    "maximize",
    "boost",
    "supercharge",
    "game-changer",
    "influential",
    "killer",
    "magical",
  
    // -- Generic Product/Service Terms
    // (You may *keep* "SaaS," "CRM," or "ERP," if those are crucial. 
    // But you can remove the generic fluff like "tools" or "solutions" 
    // since they appear in nearly every marketing headline.)
    "saas",
    "tools",
    "solutions",
    "services",
    "service",
    "platform",
    "platforms",
    "provider",
    "providers",
    "offerings",
    "bundle",
    "bundles",
    "agency",
    "agencies",
    "firm",
    "firms",
    "software",
    "apps",
    "app",
    "products",
    "product",
  
    // -- “New,” “Fresh,” “Modern,” “Updated,” etc.
    "new",
    "fresh",
    "recent",
    "updated",
    "upgrade",
    "upgrades",
    "changes",
    "improvements",
    "reimagined",
    "reborn",
    "rebranded",
  
    // -- Misc. Buzzwords
    "popular",
    "trending",
    "interesting",
    "fascinating",
    "amplify",
    "leverage",
    "optimize",
    "synergy",
    "synergies",
    "innovate",
    "disrupt",
    "disruption",
    "data-driven",
    "holistic",
    "360-degree",
    "dynamic",
    "flexible",
    "scalable",
    "scalability",
    "user-friendly",
    "intuitive",
    "cloud-based",
    "cloud"
  ]);
  
  export default stopWords;